org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=2.1.0
maven_group=network.vonix.serverutilities
archives_name=vonix_server_utilities

minecraft_version=26.1.2
neoforge_version=26.1.2.93
moddevgradle_version=2.0.140
enabled_platforms=neoforge
single_loader=true
